In [1]:
import pandas as pd
df = pd.read_csv('C:/rsource2/tour_data.csv')

## 중분류
- 중분류로 group화 한 결과 총 21542의 데이터중
    - B0201(숙박시설) : 3713
    - B0102(교통수단) : 2
    - A0401(쇼핑) : 989
    - A0502(음식점) 5528
    - 총 10232

- 위 네가지를 제외한 데이터 수 : 11310

In [3]:
df.groupby('cat2').size()

cat2
A0101    2593
A0102     122
A0201    3996
A0202     876
A0203    1286
A0204     253
A0205     267
A0206    1914
A0401     989
A0502    5528
B0102       2
B0201    3713
dtype: int64

## areacode
1. 서울 : 2548
2. 인천 : 655
3. 대전 : 366
4. 대구 : 440
5. 광주 : 324
6. 부산 : 702
7. 울산 :544
8. 세종특별자치시 : 49


31. 경기도 : 2277
32. 강원도 : 2585
33. 충청북도 : 969
34. 충청남도 : 1196
35. 경상북도 : 1912
36. 경상남도 : 2360
37. 전라북도 : 1821
38. 전라남도 : 1929
39. 제주도 : 862

In [15]:
df.groupby('areacode').size()

areacode
1.0     2548
2.0      655
3.0      366
4.0      440
5.0      324
6.0      702
7.0      544
8.0       49
31.0    2277
32.0    2585
33.0     969
34.0    1196
35.0    1912
36.0    2360
37.0    1821
38.0    1929
39.0     862
dtype: int64

### 숙박, 교통, 쇼핑, 음식점 제외하고 지역별 분류

In [6]:
df1 = df.copy()

In [8]:
list = ['B0201','B0102','A0401','A0502']

In [16]:
c = df1[~df1['cat2'].isin(list)]

In [19]:
c.groupby('areacode').size()

areacode
1.0      979
2.0      317
3.0      127
4.0      259
5.0      168
6.0      288
7.0      149
8.0       37
31.0    1267
32.0    1453
33.0     704
34.0     737
35.0    1226
36.0    1076
37.0    1002
38.0    1122
39.0     397
dtype: int64

## 지역별, 중분류를 기준으로 카운트
- 카테고리별 갯수가 10개가 되지않는 것들도 있음

In [23]:
pd.set_option('display.max_row', 500)
pd.set_option('display.max_columns', 100)

In [4]:
b = pd.DataFrame(df.groupby(by=['areacode','cat2']).size())

In [45]:
b

                  0
areacode cat2
1.0      A0101   47
         A0102    4
         A0201  199
         A0202  118
         A0203   95
         A0204   36
         A0205   55
         A0206  425
         A0401  253
         A0502  931
         B0201  385
2.0      A0101   82
         A0102    4
         A0201   83
         A0202   27
         A0203   27
         A0204   10
         A0205   10
         A0206   74
         A0401   31
         A0502  180
         B0201  127
3.0      A0101   15
         A0201   40
         A0202   13
         A0203   10
         A0204    9
         A0206   40
         A0401   10
         A0502  211
         B0201   18
4.0      A0101   16
         A0102    2
         A0201  108
         A0202   23
         A0203   36
         A0204    9
         A0205    4
         A0206   61
         A0401   19
         A0502  109
         B0201   53
5.0      A0101   25
         A0102    3
         A0201   72
         A0202   17
         A0203   12
         A0204    4
         A0205    4
         A0206   31
         A0401   13
         A0502  101
         B0201   42
6.0      A0101   45
         A0201   56
         A0202   40
         A0203   34
         A0204    9
         A0205   19
         A0206   85
         A0401   86
         A0502  187
         B0201  141
7.0      A0101   43
         A0102    2
         A0201   39
         A0202   13
         A0203   19
         A0204    6
         A0205    3
         A0206   24
         A0401   10
         A0502  314
         B0201   71
8.0      A0101    4
         A0102    1
         A0201   15
         A0202    4
         A0203    3
         A0204    1
         A0205    1
         A0206    8
         A0401    1
         A0502    7
         B0201    4
31.0     A0101  213
         A0102    3
         A0201  385
         A0202  124
         A0203  195
         A0204   36
         A0205   25
         A0206  286
         A0401   77
         A0502  630
         B0201  303
32.0     A0101  519
         A0102   16
         A0201  375
         A0202   98
         A0203  208
         A0204   25
         A0205   34
         A0206  178
         A0401   83
         A0502  630
         B0102    2
         B0201  417
33.0     A0101  124
         A0102    6
         A0201  342
         A0202   38
         A0203   82
         A0204   18
         A0205   10
         A0206   84
         A0401   50
         A0502  150
         B0201   65
34.0     A0101  177
         A0102    5
         A0201  318
         A0202   46
         A0203   96
         A0204   15
         A0205   11
         A0206   69
         A0401   41
         A0502  187
         B0201  231
35.0     A0101  260
         A0102   31
         A0201  622
         A0202   73
         A0203   90
         A0204   24
         A0205   13
         A0206  113
         A0401   79
         A0502  306
         B0201  301
36.0     A0101  276
         A0102   12
         A0201  423
         A0202   77
         A0203  116
         A0204   13
         A0205   23
         A0206  136
         A0401   56
         A0502  625
         B0201  603
37.0     A0101  208
         A0102   14
         A0201  496
         A0202   52
         A0203   94
         A0204   14
         A0205   14
         A0206  109
         A0401   62
         A0502  379
         B0201  378
38.0     A0101  367
         A0102   18
         A0201  375
         A0202   67
         A0203  121
         A0204   15
         A0205   36
         A0206  123
         A0401   79
         A0502  378
         B0201  350
39.0     A0101  172
         A0102    1
         A0201   48
         A0202   46
         A0203   48
         A0204    9
         A0205    5
         A0206   68
         A0401   39
         A0502  203
         B0201  223

In [46]:
len(b)

185

### 숙박, 교통, 쇼핑, 음식점 제외하고 지역별,중분류로 카운트

In [21]:
d = pd.DataFrame(c.groupby(by=['areacode','cat2']).size())

In [24]:
d

                  0
areacode cat2
1.0      A0101   47
         A0102    4
         A0201  199
         A0202  118
         A0203   95
         A0204   36
         A0205   55
         A0206  425
2.0      A0101   82
         A0102    4
         A0201   83
         A0202   27
         A0203   27
         A0204   10
         A0205   10
         A0206   74
3.0      A0101   15
         A0201   40
         A0202   13
         A0203   10
         A0204    9
         A0206   40
4.0      A0101   16
         A0102    2
         A0201  108
         A0202   23
         A0203   36
         A0204    9
         A0205    4
         A0206   61
5.0      A0101   25
         A0102    3
         A0201   72
         A0202   17
         A0203   12
         A0204    4
         A0205    4
         A0206   31
6.0      A0101   45
         A0201   56
         A0202   40
         A0203   34
         A0204    9
         A0205   19
         A0206   85
7.0      A0101   43
         A0102    2
         A0201   39
         A0202   13
         A0203   19
         A0204    6
         A0205    3
         A0206   24
8.0      A0101    4
         A0102    1
         A0201   15
         A0202    4
         A0203    3
         A0204    1
         A0205    1
         A0206    8
31.0     A0101  213
         A0102    3
         A0201  385
         A0202  124
         A0203  195
         A0204   36
         A0205   25
         A0206  286
32.0     A0101  519
         A0102   16
         A0201  375
         A0202   98
         A0203  208
         A0204   25
         A0205   34
         A0206  178
33.0     A0101  124
         A0102    6
         A0201  342
         A0202   38
         A0203   82
         A0204   18
         A0205   10
         A0206   84
34.0     A0101  177
         A0102    5
         A0201  318
         A0202   46
         A0203   96
         A0204   15
         A0205   11
         A0206   69
35.0     A0101  260
         A0102   31
         A0201  622
         A0202   73
         A0203   90
         A0204   24
         A0205   13
         A0206  113
36.0     A0101  276
         A0102   12
         A0201  423
         A0202   77
         A0203  116
         A0204   13
         A0205   23
         A0206  136
37.0     A0101  208
         A0102   14
         A0201  496
         A0202   52
         A0203   94
         A0204   14
         A0205   14
         A0206  109
38.0     A0101  367
         A0102   18
         A0201  375
         A0202   67
         A0203  121
         A0204   15
         A0205   36
         A0206  123
39.0     A0101  172
         A0102    1
         A0201   48
         A0202   46
         A0203   48
         A0204    9
         A0205    5
         A0206   68